/*
 FusionCharts JavaScript Library
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @version 3.9.0
*/
FusionCharts.register("module",["private","modules.renderer.js-gradientlegend",function(){function V(c,g,p){var n=c[0],m=c[1];c=c[2];n+=(g[0]-n)*p;m+=(g[1]-m)*p;g=c+(g[2]-c)*p;return{hex:(ta+(n<<16|m<<8|g).toString(16)).slice(-6),rgb:[n,m,g]}}function W(c,g){return c.maxvalue-g.maxvalue}function G(c){var g,p,n=c.colorRange||{},m=c.dataMin,A=c.dataMax,u=c.sortLegend||!1,k=c.mapByCategory||!1,y=c.defaultColor,b=c.numberFormatter,e=n.color;c=this.colorArr=[];var d,h,a;this.mapByCategory=k;"1"===n.mapbypercent&&
(this.mapbypercent=!0);if("1"===n.gradient&&!k){this.gradient=!0;p=Da(ea(n.startcolor,n.mincolor,n.code));u=ja(Da(ea(p,y,"CCCCCC")));k=this.scaleMin=I(n.startvalue,n.minvalue,this.mapbypercent?0:m);c.push({code:p,maxvalue:k,label:X(n.startlabel),codeRGB:ja(p)});if(e&&(g=e.length))for(m=0;m<g;m+=1)y=e[m],p=Da(ea(y.color,y.code)),h=I(y.value,y.maxvalue),a=I(y.minvalue),h>k&&c.push({code:p,maxvalue:h,userminvalue:a,label:X(ea(y.label,y.displayvalue)),codeRGB:ja(p)});c.sort(W);g=c.length;for(m=1;m<g;m+=
1)y=c[m],p=y.maxvalue-k,0<p?(y.minvalue=k,y.range=p,k=y.maxvalue):(c.splice(m,1),--m,--g);2<=c.length&&(this.scaleMax=k,c[m-1].label=ea(n.endlabel,c[m-1].label,c[m-1].displayvalue));1===c.length&&(h=I(n.maxvalue,this.mapbypercent?100:A),c.push({minvalue:k,maxvalue:h,range:h-k,label:n.endlabel}),this.scaleMax=h,delete c[0].code);n=c[0];A=c[c.length-1];n.code&&A.code||(p=fa(u),g=Ga((p[2]=0,p)),p=Ga((p[2]=100,p)),n.code||(n.codeRGB=g,n.code=ua(g)),A.code||(A.codeRGB=p,A.code=ua(p)));g=c.length;for(m=
1;m<g;m+=1)if(y=c[m],y.code){if(d)for(A=y,a=n.maxvalue,e=A.maxvalue-a;d<m;d+=1)u=c[d],p=V(n.codeRGB,A.codeRGB,(u.maxvalue-a)/e),u.code=p.hex,u.codeRGB=p.rgb;d=null;n=y}else d=d||m;if(void 0===this.scaleMin||void 0===this.scaleMax)this.noValidRange=!0}else if(e&&(g=e.length)){for(m=0;m<g;m+=1)y=e[m],p=ea(y.color,y.code),h=I(y.maxvalue),a=I(y.minvalue),d=ea(y.label,y.displayvalue,k?Y:b.dataLabels(a)+" - "+b.dataLabels(h)),(p&&h>a||k&&d)&&c.push({code:p,maxvalue:h,minvalue:a,label:X(d),labelId:d.toLowerCase()});
c.length?u&&c.sort(W):this.noValidRange=!0}}function Z(c,g){return g?J(100*c)/100+"%":Q(c,Y).toString()}var qa=this,c=qa.hcLib,va=qa.window,va=/msie/i.test(va.navigator.userAgent)&&!va.opera,I=c.pluckNumber,ta=c.COLOR_BLACK,g=c.COLOR_GLASS,Ea=c.FC_CONFIG_STRING,xa=c.graphics,Ga=xa.HSBtoRGB,fa=xa.RGBtoHSB,ua=xa.RGBtoHex,ja=xa.HEXtoRGB,ka=c.COMMASTRING,Y=c.BLANKSTRING,X=c.parseUnsafeString,wa=c.graphics.convertColor,Aa=c.POSITION_TOP,oa=c.POSITION_MIDDLE,za=c.POSITION_START,Ha=c.POSITION_END,ya=c.graphics.getDarkColor,
ra=c.graphics.getLightColor,ea=c.pluck,Q=c.getValidValue,sa=c.toRaphaelColor,Ba=c.hasTouch,J=Math.round,S=Math.max,U=Math.min,Ia=Math.abs,aa,Ja,Ca,Ka="rgba(192,192,192,"+(va?.002:1E-6)+")",Da=function(c){return c&&c.replace(/^#?([a-f0-9]+)/ig,"$1")};G.prototype={getColorObj:function(c){var g=this.colorArr,p=this.gradient?1:0,n=g[p],m;if(this.mapByCategory){for(c=X(c).toLowerCase();n;){if(n.labelId===c)return{code:n.code,seriesIndex:p};p+=1;n=g[p]}return{outOfRange:!0}}if(this.gradient){if(this.scaleMin<=
c&&this.scaleMax>=c){for(;n&&n.maxvalue<c;)p+=1,n=g[p];c=(c-n.minvalue)/n.range;return{code:V(g[p-1].codeRGB,n.codeRGB,c).hex}}return{outOfRange:!0}}for(;n;){if(n.maxvalue>c&&n.minvalue<=c)return{code:n.code,seriesIndex:p};n.maxvalue===c&&(m=p);p+=1;n=g[p]}return(n=g[m])&&n.maxvalue===c?{code:n.code,seriesIndex:m}:{outOfRange:!0}}};G.prototype.constructor=G;c.colorRange=G;aa=c.configureGradientLegendOptions=function(c,g){var p=c.legend,n=g.chart;p.legendSliderBorderWidth=I(n.legendpointerborderthickness,
1);p.legendSliderBorderColor=wa(ea(n.legendpointerbordercolor,ta),I(n.legendpointerborderalpha,100));p.legendSliderWidth=I(n.legendpointerwidth,n.legendpointerswidth,12);p.legendSliderHeight=I(n.legendpointerheight,n.legendpointersheight,12);p.legendColorBoxBorderColor=p.borderColor;p.legendColorBoxBorderWidth=p.borderWidth;p.legendScaleColor=wa(ea(n.legendscalelinecolor,ta),I(n.legendscalelinealpha,100));p.legendScalePadding=I(n.legendscalepadding,4);p.legendScaleLineThickness=I(n.legendscalelinethickness,
1);p.legendScaleTickDistance=I(n.legendscaletickdistance,6);p.itemStyle.cursor="default";p.interActivity=I(n.interactivelegend,1)};c.placeGLegendBlockRight=function(c,g,p,n,m){this.configureLegendOptions(c,g.chart,!0,m,p);aa(c,g);m=this.snapLiterals||(this.snapLiterals={});var A=c[Ea],u=this.smartLabel||A.smartLabel,k=c.legend,y=c.chart.spacingRight,b,e,d=k.textPadding=2,h=2*d,a=k.title.padding,f=0,ia=0,l=2*k.padding;g=I(g.chart.legendpadding,7)+k.borderWidth/2+1;var z=c.colorRange||{},x=z.colorArr,
la=z.mapbypercent,P=z.scaleMin,q=z.scaleMax-P,ba=k.legendSliderWidth,N=k.legendSliderHeight/2;e=k.legendScalePadding;var t=k.legendScaleTickDistance,v=k.itemStyle||{};b=I(parseInt(v.lineHeight,10)||12);var w=.75*b,T=p-l,D,E,r=0,F,B,C,L,H,R,K;n-=l;if(!z.noValidRange&&x&&1<(E=x.length)){--E;k.title.text!==Y&&(u.setStyle(k.title.style),b=u.getSmartText(k.title.text,T,S(b,n/4)),k.title.text=b.text,f=b.width+l,n-=ia=b.height+a);u.setStyle(v);b=u.lineHeight;T-=t+e+ba;k.colorBoxX=ba;a=S(b,T/2);T=U(T-a-4,
b);F=S(b,n/2);D=n/4;t=x[0];t.scaleLabel=Z(t.maxvalue,la);b=u.getSmartText(t.label,D,T);t.label=b.text;v=b.height;t.labelY=w-b.height/2;e=u.getSmartText(t.scaleLabel,a,F);t.scaleLabel=e.text;z=e.height/2;B=e.width;t.scaleLabelY=w-e.height/2;k.colorBoxY=S(z,b.width+h,N)+ia;t=K=x[E];t.scaleLabel=Z(t.maxvalue,la);b=u.getSmartText(t.label,D,T);t.label=b.text;v=S(v,b.height);t.labelY=w-b.height/2;e=u.getSmartText(t.scaleLabel,a,F);t.scaleLabel=e.text;B=S(B,e.width);D=e.height/2;b=S(b.width+h,D,N);t.scaleLabelY=
w-e.height/2;k.colorBoxHeight=N=n-k.colorBoxY-b;F=N-D;C=N/q;H=U(N-r,F-z)-4;for(D=1;D<E;D+=1)t=x[D],L=(t.maxvalue-P)*C,b=u.getSmartText(t.label,2*U(L-r,N-L),T),t.label=b.text,v=S(v,b.height),t.labelY=w-b.height/2,b=b.width/2,t.scaleLabel=Z(t.maxvalue,la),e=u.getSmartText(t.scaleLabel,a,2*U(L-z,F-L)),t.scaleLabel=e.text,B=S(B,e.width),R=e.height/2,t.scaleLabelY=w-e.height/2,H=U(H,(L-S(R+z,b+r)-4)*q/t.range),r=b+L,z=R+L;H=S(U(H,(U(F-z,N-r)-4)*q/K.range,.3*n),0);k.colorBoxHeight-=H;k.colorBoxWidth=v&&
v+h||15;k.height=k.totalHeight=n+ia+l-H;k.width=(B&&B+d)+k.colorBoxWidth+ba+k.legendScaleTickDistance+k.legendScalePadding+l;k.width<f&&(k.colorBoxX+=(f-k.width)/2,k.width=f);k.width>p&&(k.width=p);m.legendstartx=A.width-y-k.width;m.legendwidth=k.width;m.legendendx=m.legendstartx+m.legendwidth;m.legendheight=k.height;g+=k.width;c.chart.marginRight+=g;return g}k.enabled=!1;return 0};c.placeGLegendBlockBottom=function(c,g,p,n,m){this.configureLegendOptions(c,g.chart,!1,m,p);aa(c,g);m=this.snapLiterals||
(this.snapLiterals={});var A=c[Ea],u=this.smartLabel||A.smartLabel,k=c.legend,y=c.chart,b=y.spacingBottom,e=y.spacingLeft,y=y.spacingRight,d,h,a=k.textPadding=2,f=k.title.padding,ia=0,l=0,z=2*k.padding;g=I(g.chart.legendpadding,7)+k.borderWidth/2+1;var x=c.colorRange||{},la=x.colorArr,P=x.mapbypercent,q=x.scaleMin,ba=x.scaleMax-q,N=k.legendSliderWidth,t=k.legendSliderHeight,v=k.legendScalePadding,w=k.legendScaleTickDistance,T=k.itemStyle||{};d=I(parseInt(T.lineHeight,10)||12);var D=.75*d,E=n-z,r,
F,B,C,L=0,H,R,K;p-=z;if(!x.noValidRange&&la&&1<(F=la.length)){--F;k.title.text!==Y&&(u.setStyle(k.title.style),d=u.getSmartText(k.title.text,p,E/3),k.title.text=d.text,ia=d.width+z,E-=l=d.height+f);u.setStyle(T);d=u.lineHeight;E-=w+v+t;f=S(d,E/2);T=U(E-f-4,d);r=p/4;C=2*r;B=la[0];B.scaleLabel=Z(B.maxvalue,P);d=u.getSmartText(B.label,r,T);B.label=d.text;E=d.height;B.labelY=D-d.height/2;h=u.getSmartText(B.scaleLabel,C,f);B.scaleLabel=h.text;v=h.width/2;w=h.height;B.code||(B.code=ea(k.minColor,"CCCCCC"));
k.colorBoxX=S(v,d.width+a,N);B=x=la[F];B.scaleLabel=Z(B.maxvalue,P);d=u.getSmartText(B.label,r,T);B.label=d.text;E=S(E,d.height);B.labelY=D-d.height/2;h=u.getSmartText(B.scaleLabel,C,f);B.scaleLabel=h.text;w=S(w,h.height);B=h.width/2;d=S(d.width+a,B,N);k.colorBoxWidth=N=p-k.colorBoxX-d;C=N-B;H=N/ba;K=U(N-L,C-v)-4;for(r=1;r<F;r+=1)B=la[r],R=(B.maxvalue-q)*H,d=u.getSmartText(B.label,2*U(R-L,N-R),T),B.label=d.text,E=S(E,d.height),B.labelY=D-d.height/2,d=d.width/2,B.scaleLabel=Z(B.maxvalue,P),h=u.getSmartText(B.scaleLabel,
2*U(R-v,C-R),f),B.scaleLabel=h.text,w=S(w,h.height),h=h.width/2,K=U(K,(R-S(h+v,d+L)-4)*ba/B.range),L=d+R,v=h+R;K=S(U(K,(U(C-v,N-L)-4)*ba/x.range,.3*p),0);k.colorBoxWidth-=K;k.width=p+z-K;k.width<ia&&(k.colorBoxX+=(ia-k.width)/2,k.width=ia);k.colorBoxY=l+t;k.colorBoxHeight=E&&E+2*a||15;k.height=k.totalHeight=(w&&w+a)+k.colorBoxHeight+l+t+k.legendScaleTickDistance+k.legendScalePadding+z;k.height>n&&(k.height=n);m.legendstartx=e+.5*(A.width-e-y-k.width)+(k.x||0);m.legendwidth=k.width;m.legendendx=m.legendstartx+
m.legendwidth;m.legendstarty=A.height-b-k.height;m.legendheight=k.height;m.legendendy=m.legendstarty+m.legendheight;g+=k.height;c.chart.marginBottom+=g;return g}k.enabled=!1;return 0};Ja=function(){return{point:this}};Ca=function(c){return J(100*c)/100};c.rendererRoot.drawGradientLegendItem=function(c){var G=this,p=G.paper,n=G.options,m=G.canvasLeft,A=G.canvasTop,u=G.canvasWidth,k=G.canvasHeight,y=n.colorRange,b=n.chart.textDirection,e,d,h,a,f=n.legend,ia=I(f.padding,4),l=f.itemStyle,n=f.symbolStyle,
z=f.interActivity,x=c.elements;c=x.elementGroup.trackTooltip(!0);var la="vertical"===f.layout,P,q,ba,N,t,v,w=0,T=f.lighting3d,D=f.colorBoxWidth,E=f.colorBoxHeight,r=D,F=E,B={FCcolor:{color:Y,alpha:Y,angle:0,ratio:Y}},C=B.FCcolor,L=f.colorBoxX+ia,H=f.colorBoxY+ia,R,K,Na=f.legendColorBoxBorderColor,Oa=f.legendColorBoxBorderWidth,Fa=["M"],ga=f.legendScaleColor;v=f.legendScalePadding;var aa=f.legendScaleLineThickness,V=aa%2/2;d=f.legendScaleTickDistance;var U=f.legendSliderWidth,Z=f.legendSliderHeight;
t=F/2;a=r/2;var Q=U/2,ca=Z/2,W,da,X;K=0;var ha=ra("ABABAB",50),ia=ya("ABABAB",70),f=wa("ABABAB",100),ia=wa(ia,100),ha=wa(ha,100),ja,O={isFirst:!0},M={},pa,ma,na,fa;if(y&&(e=y.colorArr)&&1<(h=e.length)){O.toolText=pa=ba=y.scaleMin;M.toolText=ma=y=y.scaleMax;N=y-ba;O.snapPX=M.snapPX=0;O.tooltipConstraint=M.tooltipConstraint="chart";O.getLabelConfig=M.getLabelConfig=Ja;O.tooltipPos=[0,0];M.tooltipPos=[0,0];M.tooltipOffsetReference=O.tooltipOffsetReference={};M.tooltipOffsetReference.left=O.tooltipOffsetReference.left+=
m-20;M.tooltipOffsetReference.top=O.tooltipOffsetReference.top+=A;na=x.colorBox=p.group("colorBox",c);if(la){O.tooltipPos[0]=M.tooltipPos[0]=u+m;K=270;C.angle=90;m=L-U;u=L+r;A=H-ca;P=H+ca;m=J(L-U)+.5;u=J(L)+.5;A=J(H-ca)+.5;P=J(H+ca)+.5;W=J(L+r)+.5;X=J(H-2)+.5;q=J(H+2)+.5;R=J(H)+.5;k=L-Q/2;da=J(k-ca)+.5;k=J(k)+.5;t=H-ca/2;ca=J(t+ca)+.5;t=J(t)+.5;D/=2;Q=["M",m,A,"L",u,A,u,X,W,R,u,q,u,P,m,P,"Z","M",da,t,"L",k,t,"M",da,R,"L",k,R,"M",da,ca,"L",k,ca];ca=["M",m+1,A,"L",m+1,P,"M",da,t-1,"L",k,t-1,"M",da,
R-1,"L",k,R-1,"M",da,ca-1,"L",k,ca-1];t=L+r+v;P=J(t+d)+V;t=J(t)+V;R=L+a;da=h-1;for(d=0;d<h;d+=1)a=e[d],u=(a.maxvalue-ba)/N,q=F*u+H,v=J(q)+V,d?(C.ratio+=ka,C.color+=ka,C.alpha+=ka,Fa.push("L",t,v,P,v,"M",t,v),d===da?(k=Ha,v=q+2):(k=oa,v=q)):(Fa.push(t,v,"L",P,v,"M",t,v),k=za,v=q-2),C.ratio+=100*(u-w),C.color+=ea(a.code,ta),C.alpha+=ea(a.alpha,100),w=u,a.legendItem=p.text(c).attr({text:a.label,x:R,y:v,"text-anchor":k,direction:b,"vertical-align":oa}).rotate(K,R,v).css(l),a.legendSymbol=p.text(c).attr({text:a.scaleLabel,
x:P,y:q,"text-anchor":za,direction:b,"vertical-align":oa}).css(l);O.xMin=M.xMin=0;O.xMax=M.xMax=0;O.yMin=M.yMin=0;O.yMax=M.yMax=F;O.x=M.x=0;O.y=0;M.y=F;b=Z+r;e=U}else{O.tooltipPos[1]=M.tooltipPos[1]=k+A;m=J(L-Q)+.5;u=J(L+Q)+.5;A=J(H-Z)+.5;P=J(H+F)+.5;W=J(L-2)+.5;k=J(L+2)+.5;da=J(L)+.5;X=J(H)+.5;q=H-ca/2;R=J(q-ca)+.5;q=J(q)+.5;K=L-Q/2;a=J(K+Q)+.5;K=J(K)+.5;E/=2;Q=["M",m,A,"L",u,A,u,X,k,X,da,P,W,X,m,X,"Z","M",K,R,"L",K,q,"M",da,R,"L",da,q,"M",a,R,"L",a,q];ca=["M",m,A+1,"L",u,A+1,"M",K-1,R,"L",K-1,q,
"M",da-1,R,"L",da-1,q,"M",a-1,R,"L",a-1,q];v=H+F+v;K=J(v+d)+V;v=J(v)+V;q=H+t;da=h-1;for(d=0;d<h;d+=1)a=e[d],u=(a.maxvalue-ba)/N,P=r*u+L,t=J(P)+V,d?(C.ratio+=ka,C.color+=ka,C.alpha+=ka,Fa.push("L",t,v,t,K,"M",t,v),d===da?(k=za,t=P+2):(k=oa,t=P)):(Fa.push(t,v,"L",t,K,"M",t,v),k=Ha,t=P-2),C.ratio+=100*(u-w),C.color+=ea(a.code,ta),C.alpha+=ea(a.alpha,100),w=u,a.legendItem=p.text(c).attr({text:a.label,x:t,y:q,"text-anchor":k,direction:b,"vertical-align":oa}).css(l),a.legendSymbol=p.text(c).attr({text:a.scaleLabel,
x:P,y:K,"text-anchor":oa,direction:b,"vertical-align":Aa}).css(l);O.xMin=M.xMin=0;O.xMax=M.xMax=r;O.yMin=M.yMin=0;O.yMax=M.yMax=0;O.y=M.y=0;O.x=0;M.x=r;b=U;e=Z+F}x.colorBox=p.rect(na).attr({x:L,y:H,width:r,height:F,fill:sa(B),stroke:Na,strokeWidth:Oa});T&&(x.colorBoxEffect=p.rect(na).attr({x:L,y:H,width:D,height:E,fill:g,"stroke-width":0}));x.scale=p.path(c).attr({path:Fa,stroke:ga,"stroke-width":aa});ja=function(a,b,e,d,c){var f;la?(f=b*N/F+ba,d=0<b?d:d+b+.01):(f=a*N/r+ba,e=0<a?e:e+a+.01);a=Ca(f);
c?(x.slider1.translate(e,d),x.slider1Effect.translate(e,d),x.slider1Tracker.toFront().translate(e,d).tooltip(a,null,null,!0),pa=f):(x.slider2.translate(e,d),x.slider2Effect.translate(e,d),x.slider2Tracker.toFront().translate(e,d).tooltip(a,null,null,!0),ma=f);z&&(fa=clearTimeout(fa),fa=setTimeout(function(){G.setScaleRange&&G.setScaleRange(pa,ma)},100))};h=function(a,b){var e=0,d=e,c,f=this.isFirst,h=f?M:O;if(la){d=this._startY+b;0>=d&&(d=0);d>F&&(d=F);if(f?d>h.y:d<h.y)d=h.y;Ia(d-this.y)>=(this.snapPX||
0)&&(c=!0)}else{e=this._startX+a;0>=e&&(e=0);e>r&&(e=r);if(f?e>h.x:e<h.x)e=h.x;Ia(e-this.x)>=(this.snapPX||0)&&(c=!0)}c&&(ja(e,d,e-this.x,d-this.y,f),this.x=e,this.y=d)};T=function(){var a=this.isFirst;this._startX=this.x;this._startY=this.y;this._scaleStart=pa;this._scaleEnd=ma;qa.raiseEvent("LegendPointerDragStart",{pointerIndex:a?0:1,pointers:[{value:pa},{value:ma}],legendPointerHeight:Z,legendPointerWidth:U},G.logic.chartInstance)};D=function(){var a=this._scaleStart,b=this._scaleEnd;qa.raiseEvent("LegendPointerDragStop",
{pointerIndex:this.isFirst?0:1,pointers:[{value:pa},{value:ma}],legendPointerHeight:Z,legendPointerWidth:U},G.logic.chartInstance);a===pa&&b===ma||qa.raiseEvent("LegendRangeUpdated",{previousMinValue:a,previousMaxValue:b,minValue:pa,maxValue:ma},G.logic.chartInstance);delete this._scaleStart;delete this._scaleEnd};E=Ca(ba);x.slider1=p.path(c).attr({path:Q,fill:f,strokeWidth:1,stroke:ia});x.slider1Effect=p.path(c).attr({path:ca,fill:"none",strokeWidth:1,stroke:ha});Ba&&(m-=.5*(S(30,b)-b),A-=.5*(S(40,
e)-e),b=S(30,b),e=S(40,e));x.slider1Tracker=p.rect(c).attr({ishot:!0,width:b,height:e,x:m,y:A,fill:Ka,stroke:"none"}).drag(h,T,D,O,O,O).tooltip(E,null,null,!0).css(n);E=Ca(y);x.slider2=p.path(c).attr({path:Q,fill:f,strokeWidth:1,stroke:ia}).translate(M.x,M.y);x.slider2Effect=p.path(c).attr({path:ca,fill:"none",strokeWidth:1,stroke:ha}).translate(M.x,M.y);x.slider2Tracker=p.rect(c).attr({ishot:!0,width:b,height:e,x:m,y:A,fill:Ka,stroke:"none"}).translate(M.x,M.y).css(n).drag(h,T,D,M,M,M).tooltip(E,
null,null,!0)}}}]);
FusionCharts.register("module",["private","modules.renderer.js-maps",function(){var V=this,W=V.window,G=V.hcLib,Z=G.chartAPI,qa=W.document,c=G.pluck,va=G.imprint,I=G.extend2,ta=G.parseTooltext,g=G.pluckNumber,Ea=G.pluckFontSize,xa=G.HCstub,Ga=I(G.defaultPaletteOptions,{foregroundcolor:"333333",foregroundalpha:"100",foregrounddarkcolor:"111111",foregrounddarkalpha:"100",foregroundlightcolor:"666666",foregroundlightalpha:"100",backgroundlightcolor:"FFFFFF",backgroundlightalpha:"100",backgroundlightangle:90,
backgroundlightratio:"",backgroundcolor:"FFFFCC",backgroundalpha:"100",backgrounddarkcolor:"ffcc66",backgrounddarkalpha:"100",backgrounddarkangle:270,backgrounddarkratio:"",shadow:1}),fa=G.setLineHeight,ua=G.getValidValue,ja=G.parseUnsafeString,ka=G.getFirstColor,Y=G.graphics.convertColor,X=G.hashify,wa=G.getDashStyle,Aa=W.navigator.userAgent,oa=/msie/i.test(Aa)&&!W.opera,za=/AppleWebKit/.test(Aa),Ha=/stroke/ig,ya=G.hasSVG,ra=G.FC_CONFIG_STRING,ea=W.Math,Q=ea.min,sa=ea.max,Ba=ea.ceil,Aa=!/fusioncharts\.com$/i.test(W.location.hostname),
J=G.toRaphaelColor,S={left:"start",right:"end",center:"middle"},U=function(b,e){var d;b||(b={});for(d in e)b[d]=e[d];return b},Ia=function(b){var e=this.parentNode;if(!e)return!1;for(;e&&e!==qa.documentElement;){if(e===b)return!0;e=e.parentNode}return!1},aa=function(b,e){var d=e?U(b.FCcolor,e):{FCcolor:b};d.toString=J;return d},Ja=function(b,e){var d,c;this.index=e;for(c in b)d=Ga[b[c]],this[c]=d instanceof Array?d[e]:d},Ca={right:function(b,e){return e},left:function(b,e){return b-e},center:function(b,
e){return 2*Q(e,b-e)}},Ka={top:function(b,e){return e},middle:function(b,e){return 2*Q(e,b-e)},bottom:function(b,e){return b-e}},Da=function(b,e,d,c){e=Q(b,e);b=.02*e;e*=.07;c=parseFloat(c);d=parseFloat(d);return isNaN(c)||isNaN(d)?isNaN(c)?isNaN(d)?{min:b,max:e}:{min:parseInt(d/10,10),max:d}:{min:c,max:10*c}:c<d?{min:c,max:d}:{min:d,max:c}},Ma=function(b){for(var e=b&&b.length||0,d={},c;e--;)c=b[e],void 0!==c.id&&(d[c.id.toLowerCase()]=c);return d},La=function(b,e){var d,c={};e=e||1;if(!b||"object"!==
typeof b)return c;for(d in b)Ha.test(d)||("stroke-width"===d?(c[d]=Number(b[d])/e,za&&(c[d]=c[d]&&Ba(c[d])||0)):c[d]=b[d]);return c},p=function(){this.hoverEntity&&(G.raiseEvent.apply(G,this.hoverEntityEventArgs),delete this.hoverEntityEventArgs,this.hoverEntity&&this.hoverEntityAttr&&this.hoverEntity.attr(this.hoverEntityAttr),delete this.hoverEntityAttr,this.hoverEntity=null)},n=function(b,e){var c=b&&b.length||!1,h=e||"id",a={},f;if(!b)return b;for(;c--;)f=b[c],void 0!==f[h]&&(a[f[h].toLowerCase()]=
f);return a},m=function(b,e,c,h){function a(){var a=this,b=a.entityPathMap,e=a.data,c=a.items,d,e=Ma(e);v=function(){for(var h,g=b[d];g;)c[d]?a=null:((h=e[d])?h.mapItem=c[d]=new A(d,va(f(h),g),q,a.group):c[d]=new A(d,g,q,a.group),d=g.nextId&&g.nextId.toLowerCase(),g=void 0!==d&&b[d]||null);k.call(a)};w=function(){var d,h,g=t,l,v=0;for(l in P)if(!c[l]&&(d=b[l],(h=e[l])?h.mapItem=c[l]=new A(l,va(f(h),d),q,a.group):c[l]=new A(l,d,q,a.group),v+=1,delete P[l],v===g))break;v<n?(n-=v,setTimeout(w,0)):k.call(a)};
(d=x&&x.toLowerCase())?v():w()}function f(a){delete a.outlines;delete a.label;delete a.shortlabel;delete a.labelposition;delete a.labelalignment;delete a.labelconnectors;return a}function g(){var a=this.items,b=[],e,c={id:"entityLabels",items:b};for(e in a)a[e].drawLabel(b);m.addGroup(c)}function l(){var a=this.items,b;for(b in a)a[b].destroy();delete this.entityPathMap;delete this.data;delete this.chartObj;delete this.items;delete this.group}function k(){N.entities.labelsOnTop&&g.call(this);this.ready=
!0;q.checkComplete()}if(c&&c.getEntityPaths()){var x=c.getFirstId(),n=c.entityCount,P=c.getEntityPaths(!0),q=e,m=e.mapAnnotations,N=q.options,t=ya?100:50,v,w,T;this.entityPathMap=P;this.data=b;this.chartObj=q;this.items={};this.ready=!1;this.group=h||e.mapGroup;this.isReady=function(){return this.ready};a.call(this);this.drawLabels=g;this.destroy=l;this.init=a;this.initComplete=k;q.__canvasMouseOutListenerAdded||(q.__canvasMouseOutListenerAdded=!0,T=e.paper.canvas,G.addEvent(T,"mouseout",function(a){a=
a.originalEvent.relatedTarget||a.originalEvent.toElement;!oa||ya?a&&a.ownerSVGElement&&a.ownerSVGElement===T||p.call(q):a===qa.documentElement||a===e.container||a===e.container.parentElement?p.call(q):Ia.call(a,T)||p.call(q)}))}},A=function(b,e,d,h){function a(a){var b=this.featureConfig;return b&&"undefined"!==typeof b[a]?Boolean(b[a]):!1}function f(){var b;if(a.apply(this,["_ds"])){b=e.labels&&e.labels[0];if(!b)return;b=(r.useSNameInTooltip?b.shortText:b.text)+(isNaN(B)?"":r.tooltipSepChar+C)}else b=
(r.useSNameInTooltip?e.shortLabel:e.label)+(isNaN(B)?"":r.tooltipSepChar+C);return b}function k(a,b,d){b?d&&"undefined"!==typeof e.displayvalue?a=e.displayvalue:(a=c(r.includeNameInLabels?r.useShortName?a.shortText:a.text:""),r.includeValueInLabels&&!isNaN(B)&&(a=void 0===a?C:a+L+C)):a=a.text;return a}function l(a){for(var b=a&&a.length||0,e;b--;)e=a[b],this.connectorElem[b]=E.path(e,this.group).attr({transform:na.transform,stroke:Y(S,U),"shape-rendering":"crisp","stroke-width":Q})}function z(){var a=
this.chart.paper,b=ya||!oa?"litepath":"path",e=this.eJSON.outlines,c=this.group,f,h,g;f=e&&e.length||0;if(this.hasFeature("_ds")){if(this.hasFeature("isDataEnabled"))if(M)for(;f--;)h=e[f].outline,this.svgElems[f]={},this.svgElems[f].graphic=a[b](h,c).attr(na).tooltip(u).shadow(ka,d.shadowLayer);else for(;f--;)h=e[f].outline,this.svgElems[f]={},this.svgElems[f].graphic=a[b](h,c).tooltip(u).attr(na);else if(M)for(;f--;)g=I(I({},na),La(e[f].style,ma)),h=e[f].outline,this.svgElems[f]={},this.svgElems[f].graphic=
a[b](h,c).attr(g).tooltip(u).shadow(ka,d.shadowLayer);else for(;f--;)g=I(I({},na),La(e[f].style,ma)),h=e[f].outline,this.svgElems[f]={},this.svgElems[f].graphic=a[b](h,c).tooltip(u).attr(g);this.hasFeature("isDataEnabled")&&this.addMouseGestures()}else{if(M)for(;f--;)h=e[f],this.svgElems[f]={},this.svgElems[f].graphic=a[b](h,c).attr(na).tooltip(u).shadow(ka,d.shadowLayer);else for(;f--;)h=e[f],this.svgElems[f]={},this.svgElems[f].graphic=a[b](h,c).tooltip(u).attr(na);this.addMouseGestures()}return this}
function x(a){var b=this.chart;b.hoverEntityEventArgs=["entityrollout",this.eventArgs,b.fusionCharts,[b.fusionCharts.id,"rollOut",this.legacyEventArgs],a];fa&&this.isVisible&&(b.hoverEntity=this,b.hoverEntityAttr=this.revertAttr,this.attr(this.hoverAttr));G.raiseEvent("entityrollover",this.eventArgs,b.fusionCharts,[b.fusionCharts.id,"rollOver",this.legacyEventArgs],a)}function n(a,b,e){var c=this,f=c.chart,h=a.labelPosition,g=a.labelAlignment,l=c.svgElems[0]&&c.svgElems[0].graphic,v=a.style,r,w,q,
t,z;h?(l=h[0],h=h[1]):(h=l.getBBox(),l=h.x+h.width/2,h=h.y+h.height/2);g?(r=g[0],g=g[1],"right"===r?l-=W:"left"===r&&(l+=W),"top"===g?h-=W:"bottom"===g&&(h+=W)):(r="center",g="middle");w=ca;q=parseFloat(Z)/d.sFactor;t=X;z=qa;!b&&v&&(v.color&&(w=v.color),v["font-size"]&&(q=parseFloat(v["font-size"])/d.sFactor),v["font-family"]&&(t=v["font-family"]),void 0!==v["font-weight"]&&(z="bold"===v["font-weight"]));return{x:l.toString(),y:h.toString(),wrapwidth:Ca[r](ua,l+wa)-W,wrapheight:Ka[g](va,h+xa)-W,wrap:1,
type:"text",align:r,valign:g,text:k(a,b,e),tooltext:u,link:O,bgcolor:"",bordercolor:"",fillcolor:w,fontsize:q,font:t,bold:z,onclick:function(a){V.raiseEvent("entityclick",c.eventArgs,d.fusionCharts,a)},onmouseover:function(a){c!==f.hoverEntity&&(p.call(c.chart),x.call(c,a))},ontouchstart:function(a){c!==f.hoverEntity&&(p.call(c.chart),x.call(c,a))}}}function P(a){var b=this.eJSON,e=this.hasFeature("isDataEnabled"),c,d;if(!J)return null;if(this.hasFeature("_ds"))for(d=(b=b.labels)&&b.length||0;d--;)c=
b[d],a.push(this.getLabelObject(c,e,!d)),c.labelConnectors&&this.drawLabelConnectors(c.labelConnectors);else c={text:b.label,shortText:b.shortLabel,labelAlignment:b.labelAlignment,labelPosition:b.labelPosition},a.push(this.getLabelObject(c,!0,!0)),b.labelConnectors&&this.drawLabelConnectors(b.labelConnectors)}function q(a,b){var e=this.svgElems,c;for(c in e)e[c].graphic&&e[c].graphic.attr(a,b)}function m(){var a=this.svgElems,b;this.isVisible=!0;for(b in a)a[b].graphic&&a[b].graphic.attr(na)}function N(){var a=
this.svgElems,b=this.chart,e;this.isVisible=!1;b.hoverEntity===this&&p.call(b);for(e in a)a[e].graphic&&a[e].graphic.attr(pa)}function t(a){V.raiseEvent("entityclick",this.node.__entity.eventArgs,d.fusionCharts,a);void 0!==O&&d.logic.linkClickFN.call({link:O})}function v(a){var b=this.node.__entity,e=b.chart;b!==e.hoverEntity&&(p.call(e),x.call(b,a))}function w(){var a=this.eJSON,b=this.svgElems,e;this.eventArgs={value:this.value,label:a.label,shortLabel:a.shortLabel,originalId:this.originalId||this.id,
id:this.id};this.legacyEventArgs={value:this.value,lName:a.label,sName:a.shortLabel,id:this.originalId||this.id};fa&&(this.hoverAttr={fill:this.hoverColor.toString()},this.revertAttr={fill:this.fillColor.toString()},ha!==ga&&(this.hoverAttr["stroke-width"]=ha,this.revertAttr["stroke-width"]=ga));if(!isNaN(B)||da)for(e in b)void 0!==O&&b[e].graphic.css({cursor:"pointer",_cursor:"hand"}),b[e].graphic.node.__entity=this,b[e].graphic.click(t).hover(v)}function T(){var a=this.svgElems,b=this.connectorElem,
e;for(e in a)a[e].remove&&a[e].remove();for(e in b)b[e].destroy&&b[e].destroy();delete this.value;delete this.formattedValue;delete this.toolText;delete this.fillColor;delete this.hoverColor;delete this.chart;delete this.group;delete this.id;delete this.isVisible;delete this.svgElems;delete this.connectorElem;delete this.renderer;delete this.options}if(e&&d&&void 0!==b){this.chart=d;this.eJSON=e;this.group=h;this.id=b;this.originalId=e.origId;this.isVisible=!0;this.svgElems={};this.connectorElem=
{};this.featureConfig=e.options;"object"===typeof this.featureConfig&&(this.featureConfig._ds=!0);var D=d.options,E=d.paper,r=D.entities,F=r.dataLabels.style;b=e.cleanValue;var B=null===b?void 0:b,C=this.formattedValue=e.formattedValue||"",L=r.labelSepChar,H=g(e.showtooltip,r.showTooltip);b=f.call(this);h={formattedValue:C,sName:e.shortLabel,lName:e.label};var u=H?ja(c(ta(c(e.tooltext,r.tooltext,b),[1,2,7,38,39],h,e))):"",K,y,A,J=g(e.showlabel,r.showLabels);h=c(e.bordercolor,r.borderColor);b=c(e.borderalpha,
r.borderAlpha);var H=1===r.scaleBorder,ga=g(e.borderthickness,r.borderThickness),S=c(e.labelconnectorcolor,r.connectorColor),U=c(e.labelconnectoralpha,r.connectorAlpha),Q=g(e.labelconnectorthickness,r.connectorThickness),X=c(e.font,F.fontFamily),Z=g(parseInt(e.fontsize,10),parseInt(F.fontSize,10)),ca=c(e.fontcolor,F.color),W=g(e.labelpadding,r.labelPadding),da=r.hoverOnNull,fa=g(e.showhovereffect,e.usehovercolor,da?r.showHoverEffect:isNaN(B)?0:r.showHoverEffect),ha=g(e.borderhoverthickness,e.hoverborderthickness,
r.hoverBorderThickness),qa=g(e.fontbold,0),O=e.link,M=r.shadow;A=!oa||ya;F=d.sFactor/r.baseScaleFactor;K=d.strokeWidth;y=(A?r.baseScaleFactor:1)*K;var pa=r.hiddenEntityFillObject||(r.hiddenEntityFillObject={fill:aa({color:r.hiddenEntityColor,alpha:r.hiddenEntityAlpha}).toString()}),ma,na,ka,D=D[ra],ua=D._labelBaseWidth,va=D._labelBaseHeight,wa=D._labelXOffset,xa=D._labelYOffset;A?(ga=H?ga*y:ga/F,Q/=F,ma=H?F:d.sFactor,za&&(ga=ga&&Ba(ga)||0,Q=Q&&Ba(Q)||0)):(ga=H?ga*K:ga,ma=H?d.scaleFactor:r.baseScaleFactor);
r.showHiddenEntityBorder||(pa["stroke-width"]=0);void 0===ha?ha=ga:A?(ha=H?ga*y:ha/F,za&&(ha=ha&&Ba(ha)||0)):ha=H?ha*K:ha;!r.showNullEntityBorder&&isNaN(B)&&(ga=0);void 0!==c(e.color,e.alpha,e.angle,e.ratio)?(H=c(e.color,r.fillColor),D=c(e.alpha,r.fillAlpha),K=c(e.angle,r.fillAngle),y=c(e.ratio,r.fillRatio),A=aa({color:H,alpha:D,angle:K,ratio:y})):(r.fillColorObject||(r.fillColorObject=aa({color:c(r.fillColor),alpha:c(r.fillAlpha),angle:c(r.fillAngle),ratio:c(r.fillRatio)})),r.emptyColorObject||(r.emptyColorObject=
aa({color:c(r.nullEntityColor),alpha:c(r.nullEntityAlpha),angle:c(r.nullEntityAngle),ratio:c(r.nullEntityRatio)})),A=isNaN(B)?r.emptyColorObject:r.fillColorObject,H=A.FCcolor.color,D=A.FCcolor.alpha,K=A.FCcolor.angle,y=A.FCcolor.ratio);""===u&&(H=0);na={transform:ya||!oa?"":d.transformStr,stroke:Y(h,b),"stroke-width":ga,fill:(this.fillColor=A).toString()};h=D.split(",");ga&&h.push(b);ka={scalefactor:[F,d.sFactor],opacity:sa.apply(ea,h)/100};fa&&(void 0!==c(e.fillhovercolor,e.fillhoveralpha,e.fillhoverangle,
e.fillhoverratio,e.hoverfillcolor,e.hoverfillalpha,e.hoverfillratio,e.hoverfillangle)?(H=c(e.fillhovercolor,e.hoverfillcolor,r.hoverFillColor),D=c(e.fillhoveralpha,e.hoverfillalpha,r.hoverFillAlpha),K=c(e.fillhoverangle,e.hoverfillangle,r.hoverFillAngle),y=c(e.fillhoverratio,e.hoverfillratio,r.hoverFillRatio),b=aa({color:H,alpha:D,angle:K,ratio:y})):(r.hoverColorObject||(r.hoverColorObject=aa({color:r.hoverFillColor,alpha:r.hoverFillAlpha,angle:r.hoverFillAngle,ratio:r.hoverFillRatio})),b=r.hoverColorObject),
this.hoverColor=b);this.value=B;this.addMouseGestures=w;this.attr=q;this.draw=z;this.drawLabel=P;this.getLabelObject=n;this.destroy=T;this.show=m;this.hide=N;this.hasFeature=a;this.drawLabelConnectors=l;z.call(this);r.hideNullEntities&&void 0===B&&this.hide()}},u=function(b,e,c,h){this.id=b;this.definition=e;this.application=c;this.rapi=h;this.markerLabel=this.markerShape=this.label=this.options=this.value=this.hasValue=null;this.drawOptions={shape:null,label:null};this.drawComplete=!1;if(b=h.options)this._conf=
b[ra];this.init()},k=function(b,e,c,h){this.options=b;this.from=e;this.to=c;this.api=h;if(b=h.options)this._conf=b[ra]},y=function(b,e){function d(){var b=x.definition,c=n(b)||{},d=n(x.application)||{},h=x.shapes,g,l;if(b&&b.length){if(h&&h.length)for(b=h.length;b;--b)if(g=h[b-1],l=g.id.toLowerCase())a[l]=g;for(l in c){g=c[l];h=new u(l,g,d[l],e);if(b=h.getShapeId())h.shapeObj=a[b];f[l]=h}}}function h(){var b=x.items,c=x.shapes,d,h,g,l;if(b&&b.length){if(c&&c.length)for(d=c.length;d;--d)if(h=c[d-1],
l=h.id.toLowerCase())a[l]=h;for(d=b.length;d--;)if(h=b[d],l=h.id&&h.id.toLowerCase())void 0!==h.value&&""!==h.value&&parseFloat(h.value),h.mapItem=c=new u(l,h,null,e),g=c.getShapeId(),h.__hideMarker&&(c._isHidden=!0),g&&(c.shapeObj=a[g]),f[l]=c}}var a={},f={},g=[],l=e.options.markers,z=e.options.connectors,x=b,p=e.mapAnnotations,m,q,ba,N,t=[];this.items=f;(function(){var a=u.prototype,b=k.prototype,d;d=Boolean(c(l.hoverFillColor,l.hoverFillAlpha,l.hoverFillAngle,l.hoverFillRatio,l.hoverBorderThickness,
l.hoverBorderColor,l.hoverBorderAlpha));a.markerFont=l.dataLabels.style.fontFamily;a.markerFontSize=l.dataLabels.style.fontSize;a.markerFontColor=l.dataLabels.style.fontColor;a.showMarkerTooltip=l.showTooltip;a.showHoverEffect=d;a.tooltext=l.tooltext;a.showMarkerLabels=l.showLabels;a.markerLabelPadding=l.labelPadding;a.labelWrapWidth=l.labelWrapWidth;a.labelWrapHeight=l.labelWrapHeight;a.labelSepChar=l.labelSepChar;a.tooltipSepChar=l.tooltipSepChar;a.fillColor=l.fillColor;a.fillAlpha=l.fillAlpha;
a.fillRatio=l.fillRatio;a.fillAngle=l.fillAngle;a.hoverFillColor=l.hoverFillColor;a.hoverFillAlpha=l.hoverFillAlpha;a.hoverFillRatio=l.hoverFillRatio;a.hoverFillAngle=l.hoverFillAngle;a.startAngle=l.startAngle;a.shapeId=l.shapeId;a.borderThickness=l.borderThickness;a.borderColor=l.borderColor;a.borderAlpha=l.borderAlpha;a.hoverBorderThickness=l.hoverBorderThickness;a.hoverBorderColor=l.hoverBorderColor;a.hoverBorderAlpha=l.hoverBorderAlpha;a.markerRadius=l.radius;a.autoScale=l.autoScale?e.sFactor:
1;a.shadow=l.shadow;a.applyAll=l.applyAll;a.dataEnabled=l.dataEnabled;a.valueToRadius=l.valueToRadius;a=Boolean(c(z.hoverthickness,z.hovercolor,z.hoveralpha));b.showHoverEffect=a;b.showTooltip=z.showTooltip;b.tooltext=z.tooltext;b.thickness=z.thickness;b.color=z.color;b.alpha=z.alpha;b.hoverThickness=z.hoverthickness;b.hoverColor=z.hovercolor;b.hoverAlpha=z.hoveralpha;b.dashed=z.dashed;b.dashlen=z.dashLen;b.dashgap=z.dashGap;b.font=z.font;b.fontsize=z.fontSize;b.fontcolor=z.fontColor;b.bgcolor=z.labelBgColor;
b.bordercolor=z.labelBorderColor;b.shadow=z.shadow;b.hideOpen=z.hideOpen})();l.dataEnabled?h():d();(function(){var b=f,e=[],c,d,h,g;q=p.addGroup({items:[]});m=p.addGroup({fillalpha:"100",items:e});for(g in b)c=null,d=b[g],h=d.getShapeId(),d&&!d._isHidden&&(h&&(d.shapeObj=a[h]),c=d.draw()),c&&(d._annotationIndex=e.length,d.markerShape=c.markerShape&&m.addItem(c.markerShape),d.markerLabel=c.markerLabel&&q.addItem(c.markerLabel))})();(function(){var a=z.showLabels,b=x.connectors,c=b&&b.length,d=[],h=
[],l,q,p;if(c)for(t.push({id:"connectorLabels",fillalpha:"100",items:h}),t.push({id:"connectors",fillalpha:"100",items:d});c--;)if(p=b[c],p.from&&p.to&&(l=f[p.from.toLowerCase()],q=f[p.to.toLowerCase()],l&&q&&(!z.hideOpen||!l._isHidden&&!q._isHidden)&&(g.push(q=new k(p,l,q,e)),q.connectJSON=l=q.computeConnectorJSON())))d.push(l),l.label&&a&&h.push(q.getLabelJSON())})();N=t.length;for(e.internalAnnotations={};N--;)ba=t.shift(),ba.id?e.internalAnnotations[ba.id]=p.addGroup(ba):p.addGroup(ba);this.addMarkerItem=
function(b){var c,d;if((c=b.id.toLowerCase())&&!f[c]){delete b.value;b=new u(c,b,null,e);if(d=b.getShapeId())b.shapeObj=a[d];f[c]=b;c=b.draw();m&&q&&(b.markerShape=c.markerShape&&m.addItem(c.markerShape,!0),b.markerLabel=c.markerLabel&&q.addItem(c.markerLabel,!0))}}};k.prototype={constructor:k,computeConnectorJSON:function(){var b=this.api,e=this.options,d=this.from,h=this.to,a=e.link,f=e.label,k=g(e.showtooltip,this.showTooltip),l=k?c(e.tooltext,this.tooltext):"",z=c(e.thickness,this.thickness),
x=c(e.color,this.color),n=c(e.alpha,this.alpha),m=g(e.showhovereffect,this.showHoverEffect),q=c(e.hovercolor,this.hoverColor,x),u=c(e.hoveralpha,this.hoverAlpha,n),N=c(e.hoverthickness,this.hoverThickness,z),t=c(e.dashed,this.dashed),v=g(e.dashlen,this.dashlen),w=g(e.dashgap,this.dashgap),y;l&&(this.tooltext=l=ja(ta(l,[3,40,41,42,43],{label:f,fromId:d.definition.id,toId:h.definition.id,fromLabel:d.definition.label,toLabel:h.definition.label},e)));return d&&h?(y={fromMarkerId:d.id,toMarkerId:h.id,
label:f},I({type:"line"},{x:d.definition.x,y:d.definition.y,tox:h.definition.x,toy:h.definition.y,dashed:t,dashlen:v,dashgap:w,link:a,tooltext:k?l:"",thickness:z,color:x,alpha:n,label:f,showshadow:this.shadow,_hovereffect:m,_defaultattrs:{stroke:aa({color:x,alpha:n}).toString(),"stroke-width":z},_hoverattrs:{stroke:aa({color:q,alpha:u}).toString(),"stroke-width":N},onmouseover:function(a){var e=a.data,c=e.wrapper;c&&e.options._hovereffect&&(p.call(b),c.attr(e.options._hoverattrs));V.raiseEvent("connectorrollover",
y,b.fusionCharts,a)},onmouseout:function(a){var e=a.data,c=e.wrapper;c&&e.options._hovereffect&&c.attr(e.options._defaultattrs);V.raiseEvent("connectorrollout",y,b.fusionCharts,a)},onclick:function(a){V.raiseEvent("connectorClick",y,b.fusionCharts,a)}})):null},getLabelJSON:function(){var b=this.connectJSON;return I({type:"text"},{x:((Number(b.x)+Number(b.tox))/2).toString(),y:((Number(b.y)+Number(b.toy))/2).toString(),text:b.label,align:"center",valign:"middle",font:this.font,fontsize:this.fontsize/
this.api.sFactor,fillcolor:this.fontcolor,bgcolor:this.bgcolor,bordercolor:this.bordercolor,tooltext:this.tooltext})}};u.prototype={constructor:u,init:function(){var b;b=this.options=I({},this.definition);this.dataEnabled?isNaN(b.value)||""===b.value||(this.value=parseFloat(b.value),this.hasValue=!0):this.applyAll?this.options=I(b,this.application):this.application&&(this.options=I(b,this.application))},getShapeId:function(){return this.options.shapeid&&this.options.shapeid.toLowerCase()||this.shapeId},
getLabelOptions:function(b,e,c,h,a){var f,g=b&&b.toLowerCase();this.getLabelAlignment[g]||(g="center");b=Number(c.x);f=Number(c.y);c=void 0===h||void 0===a?c.radius||0:/^(top|bottom)$/ig.test(g)&&.5*a||/^(left|right)$/ig.test(g)&&.5*h||0;c=Number(c)+Number(e);return this.getLabelAlignment[g](b,f,c)},draw:function(){if(this.options){var b=this,e=b.rapi,d=b._conf,h=e.translateX,a=e.translateY,f=b.options,k=b.getShapeId(),l=f.scale||1,z=f.label||"",x=(f.labelpos||"top").toLowerCase(),n=void 0===f.formattedValue?
void 0:f.formattedValue,m=f.tooltext||b.tooltext,q=g(f.radius,b.markerRadius)*l*b.autoScale||1E-4,u=c(f.fillcolor,f.color,b.fillColor),N=c(f.fillalpha,f.alpha,b.fillAlpha),t=c(f.fillratio,b.fillRatio),v=c(f.fillangle,b.fillAngle),w=g(f.borderthickness,b.borderThickness),y=c(f.bordercolor,b.borderColor),D=c(f.borderalpha,b.borderAlpha),E=f.labelpadding||b.markerLabelPadding,r,F;if(k){m=m?ja(ta(m,[1,2,3],{formattedValue:n,label:z},f)):n?z+b.tooltipSepChar+n:z;void 0!==n&&null!==n?z=z+b.labelSepChar+
n:isNaN(l)?l=1:0>l?l=0:5<l&&(l=5);r=function(){var c=b.markerShape,d=c.options,f=c.bounds,g=d._markerEventArgs;(c=c.wrapper)&&d.hovereffect&&(p.call(e),c.attr(d._hoverattrs));g||(g=d._markerEventArgs={x:f.x1/f.xs,y:f.y1/f.ys,scaledX:f.x1,scaledY:f.y1,chartX:h+f.x1,chartY:a+f.y1,id:d._markerId,label:d._markerLabel});V.raiseEventGroup(b.id,"markerRollOver",g,e.fusionCharts,b,void 0,void 0,void 0)};F=function(){var a=b.markerShape,c=a.wrapper;c&&a.options.hovereffect&&c.attr(a.options._defaultattrs);
V.raiseEventGroup(b.id,"markerRollOut",a.options._markerEventArgs,e.fusionCharts,void 0,void 0,void 0)};f={x:f.x.toString(),y:f.y.toString(),fillcolor:u,fillalpha:N,fillratio:t,fillangle:v,borderthickness:w,bordercolor:y,borderalpha:D,hovereffect:c(f.showhovereffect,b.showHoverEffect),radius:q.toString(),tooltext:b.showMarkerTooltip?m:"",link:f.link,showshadow:g(f.showshadow,b.shadow),_markerLabel:z,_markerId:f.id,id:(f.id+"").toLowerCase(),onmouseover:function(){r()},onmouseout:function(){F()},onclick:function(a){V.raiseEvent("markerClick",
a.data.options._markerEventArgs,e.fusionCharts,a)}};"triangle"===k?I(f,{type:"polygon",sides:3,startangle:b.startAngle}):"diamond"===k?I(f,{type:"polygon",sides:4,startangle:b.startAngle}):"arc"===k?I(f,{type:"arc",startangle:0,endangle:360,innerradius:.6*q}):"circle"===k?f.type="circle":(E=b.getShapeArgs(),b.dataEnabled&&b.valueToRadius&&void 0!==f.radius?delete E.radius:(!E.radius&&(E.radius=b.markerRadius),E.radius=E.radius*l*b.autoScale),I(f,E));I(f,{hoverfillcolor:c(f.fillhovercolor,b.hoverFillColor,
f.fillcolor),hoverfillalpha:c(f.fillhoveralpha,b.hoverFillAlpha,f.fillalpha),hoverfillratio:c(f.fillhoverratio,b.hoverFillRatio,f.fillratio),hoverfillangle:c(f.fillhoverangle,b.hoverFillAngle,f.fillangle),hoverborderthickness:g(f.borderhoverthickness,b.hoverBorderThickness,f.borderthickness),hoverbordercolor:c(f.borderhovercolor,b.hoverBorderColor,f.bordercolor),hoverborderalpha:c(f.borderhoveralpha,b.hoverBorderAlpha,f.borderalpha)});f._defaultattrs={fill:aa({alpha:f.fillalpha,color:f.fillcolor,
angle:f.fillangle,ratio:f.fillratio}).toString(),"stroke-width":"0"!==f.showborder?f.borderthickness:0,stroke:Y(f.bordercolor,f.borderalpha)};f._hoverattrs={fill:aa({alpha:f.hoverfillalpha,color:f.hoverfillcolor,angle:f.hoverfillangle,ratio:f.hoverfillratio}).toString(),"stroke-width":"0"!==f.showborder?f.hoverborderthickness:0,stroke:Y(f.hoverbordercolor,f.hoverborderalpha)};"image"===f.type&&(f.borderthickness=f.borderthickness||0,f.onload=function(a){var b=this.options,c=a.width;a=a.height;var d=
(Number(b.x)-c/(2*e.sFactor))*e.sFactor,b=(Number(b.y)-a/(2*e.sFactor))*e.sFactor,f;if(c&&a)for(f in{wrapper:1,tracker:1})this[f]&&this[f].attr({x:d,y:b,width:c,height:a})});b.drawOptions.shape=f;if(!b.showMarkerLabels)return{markerShape:f};E=f.labelpadding||b.markerLabelPadding;l=b.getLabelOptions(x,E,f);x=l.align;k=l.valign;m=d._labelBaseWidth;n=d._labelBaseHeight;q=d._labelXOffset;d=d._labelYOffset;m=b.labelWrapWidth?b.labelWrapWidth:b.getWrapWidth[x](m,Number(l.x)+q);d=b.labelWrapHeight?b.labelWrapHeight:
b.getWrapHeight[k](n,Number(l.y)+d);m>E&&(m-=E);d>E&&(d-=E);b.drawOptions.label="center"==x&&"middle"==k?I({type:"text"},{text:z,tooltext:f.tooltext,x:l.x,y:l.y,align:x,valign:l.valign,wrap:1,wrapwidth:m,wrapheight:d,fontsize:b.markerFontSize/e.sFactor,font:b.markerFont,fillcolor:b.markerFontColor,onmouseover:function(){r()},onmouseout:function(){F()}}):I({type:"text"},{text:z,tooltext:f.tooltext,x:l.x,y:l.y,align:x,valign:l.valign,wrap:1,wrapwidth:m,wrapheight:d,fontsize:b.markerFontSize/e.sFactor,
font:b.markerFont,fillcolor:b.markerFontColor});return{markerShape:f,markerLabel:b.drawOptions.label}}}},show:function(){this.setMarkerVisibility(!0)},hide:function(){this.setMarkerVisibility(!1)},setMarkerVisibility:function(b){var e=this.rapi&&this.rapi.internalAnnotations;if(e=(e=e&&e.markers)&&e.items)if(e=e[this._annotationIndex])this._origFill||(this._origFill=aa({alpha:e.fillAlpha,color:e.fillColor,angle:e.fillAngle,ratio:e.fillRatio}),this._hideFill=aa({alpha:"0",color:e.fillColor,angle:e.fillAngle,
ratio:e.fillRatio})),b?e.wrapper.attr({fill:this._origFill}):e.wrapper.attr({fill:this._hideFill})},getShapeArgs:function(){var b=I({},this.shapeObj),e;return b?("polygon"===b.type?3>b.sides?b.type="circle":b.startangle=this.startAngle:"arc"===b.type&&(e=(b.radius||this.markerRadius)*this.autoScale,b.radius=e,b.innerradius=b.innerradius&&b.innerradius*this.autoScale||.6*e),b):null},destroy:function(){var b=this.markerShape,e=this.markerLabel,c;b&&b.destroy();e&&e.destroy();for(c in this)delete this[c]},
getLabelAlignment:{top:function(b,e,c){return{x:b.toString(),y:(e-c).toString(),align:"center",valign:"top"}},left:function(b,e,c){return{x:(b-c).toString(),y:e.toString(),align:"right",valign:"middle"}},right:function(b,e,c){return{x:(b+c).toString(),y:e.toString(),align:"left",valign:"middle"}},bottom:function(b,c,d){return{x:b.toString(),y:(c+d).toString(),align:"center",valign:"bottom"}},center:function(b,c){return{x:b.toString(),y:c.toString(),align:"center",valign:"middle"}}},getWrapWidth:{right:function(b,
c){return c},left:function(b,c){return b-c},center:function(b,c){return 2*Q(c,b-c)}},getWrapHeight:{top:function(b,c){return c},middle:function(b,c){return 2*Q(c,b-c)},bottom:function(b,c){return b-c}}};U(G.eventList,{entityrollover:"FC_Event",entityrollout:"FC_Event"});Z("geo",{name:"geo",friendlyName:"Map",revision:1,creditLabel:Aa,standaloneInit:!1,annotationInteractionEvents:!1,charttopmargin:10,chartrightmargin:10,chartbottommargin:10,chartleftmargin:10,baseWidth:400,baseHeight:300,baseScaleFactor:1,
defaultSeriesType:"geo",rendererId:"maps",entities:{},draw:function(b,c){var d=this.renderer,h=this.chartInstance;d||(d=this.renderer=new Z("renderer."+this.rendererId));this.updateDefaultAnnotations();h.addEventListener("internal.mapdrawingcomplete",function(a,b){c&&c.apply(this,[b.renderer]);a.detachHandler()});return d.init(this,b,function(a){a.checkComplete()})},chart:function(b,e){I(this.dataObj.chart,{charttopmargin:this.dataObj.chart.maptopmargin,chartrightmargin:this.dataObj.chart.maprightmargin,
chartbottommargin:this.dataObj.chart.mapbottommargin,chartleftmargin:this.dataObj.chart.mapleftmargin,animation:this.dataObj.chart.animation||"0"});var d=this.dataObj,h=xa(d,b,e,this),a=d.chart,f=d.markers,k=h.chart,l=h[ra],z=k.useRoundEdges=1===g(a.useroundedges),x=z?1:0,z=z?0:1,p=k.use3DLighting=1===g(a.use3dlighting,1),n=I({},h.tooltip.style),q=new Ja(this.colorPaletteMap,(0<a.palette&&6>a.palette?a.palette:g(this.paletteIndex,1))-1),m=c(a.basefont,"Verdana,sans"),u=Ea(a.basefontsize,10),t=c(a.basefontcolor,
q.basefontcolor),v=Ea(a.outcnvbasefontsize,u),w=c(a.outcnvbasefont,m),y=v+"px",D=X(c(a.outcnvbasefontcolor,t)),E=c(a.bgcolor,a.canvasbgcolor,q.canvasbgcolor),r=c(a.bgalpha,a.canvasbgalpha,q.canvasbgalpha),F=g(a.usevaluesformarkers,d.markers&&d.markers.items&&d.markers.items.length,!(d.markers&&d.markers.application&&d.markers.application.length&&d.markers.definition&&d.markers.definition.length)),B,C,L,H,A,K,J,u=u+"px",t=X(t);this.realtimeEnabled&&this.postHCJSONCreation&&this.postHCJSONCreation.call(this,
h);k.events.click=this.linkClickFN;l.numberFormatter=this.numberFormatter;I(l,{width:b,height:e,showTooltip:g(a.showtooltip,this.showtooltip,1),showHoverEffect:g(a.showhovereffect,1),tooltipSepChar:c(a.tooltipsepchar,", "),showValues:g(a.showvalues,this.showValues,1),showCanvasBG:c(a.showcanvasbg,1),useValuesForMarkers:F,adjustViewPortForMarkers:g(a.adjustviewportformarkers,F),flatScrollBars:g(a.flatscrollbars,0),scrollBar3DLighting:g(a.scrollbar3dlighting,1),outCanvasStyle:{fontFamily:w,color:D,
fontSize:y},inCanvasStyle:{fontFamily:m,fontSize:u,color:t}});fa(l.outCanvasStyle);B=fa(l.inCanvasStyle);l.trendStyle=l.outCanvasStyle;"0"==l.showCanvasBG&&(r="0");C=c(a.entitybordercolor,a.bordercolor,q.plotbordercolor);L=c(a.entityfillcolor,a.fillcolor,q.plotfillcolor);H=c(a.entityfillalpha,a.fillalpha,q.plotfillalpha);A=c(a.entityfillratio,a.fillratio,q.plotfillratio);K=c(a.entityfillangle,a.fillangle,q.plotfillangle);J=c(a.nullentityfillcolor,a.nullentitycolor,L);F=g(a.showcanvasborder,z)?g(a.canvasborderthickness,
1):0;I(h,{chart:{emulateFlashGutter:g(a._emulateflashgutter,1),defaultSeriesType:this.defaultSeriesType,paletteIndex:q.index,borderRadius:g(a.canvasborderradius,0),borderColor:Y(c(a.canvasbordercolor,q.canvasbordercolor),c(a.canvasborderalpha,q.canvasborderalpha)),borderWidth:F,borderDashStyle:g(a.canvasborderdashed,0)?wa(g(a.canvasborderdashlen,4),g(a.canvasborderdashgap,2),F):"none",backgroundColor:aa({color:E,alpha:r,angle:c(a.bgangle,a.canvasbgangle,q.canvasbgangle),ratio:c(a.bgratio,a.canvasbgratio,
q.canvasbgratio)}),plotBorderColor:"#ffffff",plotBorderWidth:0,plotBackgroundColor:aa({color:"#ffffff",alpha:0}),bgSWF:c(a.bgimage,a.bgswf),bgSWFAlpha:g(a.bgimagealpha,a.bgswfalpha,100),bgImageScale:g(a.bgimagescale,100),bgImageDisplayMode:c(a.bgimagedisplaymode,"none").toLowerCase(),logoURL:ua(a.logourl),logoPosition:c(a.logoposition,"tl").toLowerCase(),logoAlpha:g(a.logoalpha,100),logoLink:ua(a.logolink),logoScale:g(a.logoscale,100),logoLeftMargin:g(a.logoleftmargin,0),logoTopMargin:g(a.logotopmargin,
0),toolbar:function(){var d={button:{}},f=d.button,h;f.scale=g(a.toolbarbuttonscale,1.15);f.width=g(a.toolbarbuttonwidth,15);f.height=g(a.toolbarbuttonheight,15);f.radius=g(a.toolbarbuttonradius,2);f.spacing=g(a.toolbarbuttonspacing,5);f.fill=Y(c(a.toolbarbuttoncolor,"ffffff"));f.labelFill=Y(c(a.toolbarlabelcolor,"cccccc"));f.symbolFill=Y(c(a.toolbarsymbolcolor,"ffffff"));f.hoverFill=Y(c(a.toolbarbuttonhovercolor,"ffffff"));f.stroke=Y(c(a.toolbarbuttonbordercolor,"bbbbbb"));f.symbolStroke=Y(c(a.toolbarsymbolbordercolor,
"9a9a9a"));f.strokeWidth=g(a.toolbarbuttonborderthickness,1);f.symbolStrokeWidth=g(a.toolbarsymbolborderthickness,1);h=f.symbolPadding=g(a.toolbarsymbolpadding,5);f.symbolHPadding=g(a.toolbarsymbolhpadding,h);f.symbolVPadding=g(a.toolbarsymbolvpadding,h);h=d.position=c(a.toolbarposition,"tr").toLowerCase();switch(h){case "tr":case "tl":case "br":case "bl":break;default:h="tr"}f=d.hAlign="left"===(""+a.toolbarhalign).toLowerCase()?"l":h.charAt(1);h=d.vAlign="bottom"===(""+a.toolbarvalign).toLowerCase()?
"b":h.charAt(0);d.hDirection=g(a.toolbarhdirection,"r"===f?-1:1);d.vDirection=g(a.toolbarvdirection,"b"===h?-1:1);d.vMargin=g(a.toolbarvmargin,6);d.hMargin=g(a.toolbarhmargin,10);d.x=g(a.toolbarx,"l"===f?0:b);d.y=g(a.toolbary,"t"===h?0:e);return d}()},title:{text:ja(a.caption),offsetX:Number(a.captionxshift),offsetY:Number(a.captionyshift),position:c(a.captionposition,void 0!==a.captionxshift||void 0!==a.captionyshift?"top left":"top"),padding:g(a.captionpadding,10),style:{fontFamily:c(a.captionfontfamily,
w),color:c(a.captionfontcolor,D).replace(/^#?([a-f0-9]+)/ig,"#$1"),fontSize:g(a.captionfontsize,v+3)+"px",fontWeight:0===g(a.captionfontbold)?"normal":"bold"}},subtitle:{text:ja(a.subcaption),style:{fontFamily:c(a.subcaptionfontfamily,a.captionfontfamily,w),color:c(a.subcaptionfontcolor,a.captionfontcolor,D).replace(/^#?([a-f0-9]+)/ig,"#$1"),fontSize:g(a.subcaptionfontsize,g(sa(a.captionfontsize-3,1),v))+"px",fontWeight:0===g(a.subcaptionfontbold)?"normal":"bold"}},orphanStyles:{defaultStyle:{style:I({},
l.inCanvasStyle)}},tooltip:{enabled:0!==l.showTooltip,style:{fontFamily:m,fontSize:u,lineHeight:B,color:t,padding:g(a.tooltippadding,this.tooltippadding,3)+"px",backgroundColor:Y(c(n.backgroundColor,a.tooltipbgcolor,q.tooltipbgcolor),c(a.tooltipbgalpha,"100")),borderColor:Y(c(n.borderColor,a.tooltipbordercolor,q.tooltipbordercolor),c(a.tooltipborderalpha,"100")),borderWidth:g(a.tooltipborderthickness,z)+"px",borderRadius:g(a.tooltipborderradius,x+1)+"px"},constrain:g(a.constraintooltip,1),shadow:g(a.showtooltipshadow,
a.showshadow,1)?{enabled:!0,opacity:sa(g(a.tooltipbgalpha,100),g(a.tooltipborderalpha,100))/100}:!1},legend:{itemStyle:{fontFamily:c(a.legenditemfont,w),fontSize:g(a.legenditemfontsize,v)+"px",color:X(c(a.legenditemfontcolor,D)),fontWeight:g(a.legenditemfontbold)?"bold":"normal"},itemHiddenStyle:{fontFamily:w,fontSize:y,color:X(c(a.legenditemhiddencolor,D))},itemHoverStyle:{color:X(c(a.legenditemhoverfontcolor,a.legenditemfontcolor,D))},enabled:g(a.showlegend,1),title:{text:ja(a.legendcaption),style:{fontFamily:c(a.legendcaptionfont,
w),fontSize:g(a.legendcaptionfontsize,v)+"px",color:X(c(a.legendcaptionfontcolor,D)),fontWeight:g(a.legendcaptionfontbold,1)?"bold":"normal"},align:S[c(a.legendcaptionalignment)]},position:c(a.legendposition,0===g(d.colorrange&&d.colorrange.gradient,0)?"right":"bottom"),backgroundColor:c(a.legendbgcolor,q.bgcolor),backgroundAlpha:c(a.legendbgalpha,"100"),borderColor:c(a.legendbordercolor,q.legendbordercolor),borderThickness:c(a.legendborderthickness,"1"),borderAlpha:c(a.legendborderalpha,"100"),shadow:g(a.legendshadow,
1),allowDrag:g(a.legendallowdrag,0),scroll:{scrollBgColor:c(a.legendscrollbgcolor,a.scrollcolor,"AAAAAA"),scrollBtnColor:c(a.legendscrollbtncolor,"BBBBBB"),scrollBarColor:c(a.legendscrollbarcolor,"CCCCCC")},reversed:g(a.reverselegend,0),interactive:g(a.interactivelegend,0),minColor:J,lighting3d:p},markers:{dataLabels:{style:{fontFamily:c(a.markerfont,m),fontSize:g(a.markerfontsize,parseInt(u,10)),fontColor:c(a.markerfontcolor,t)}},showTooltip:g(a.showmarkertooltip,l.showTooltip),showLabels:g(a.showmarkerlabels,
a.showlabels,1),showHoverEffect:g(a.showmarkerhovereffect,1),labelPadding:c(a.markerlabelpadding,"5"),labelWrapWidth:g(a.markerlabelwrapwidth,0),labelWrapHeight:g(a.markerlabelwrapheight,0),fillColor:c(a.markerfillcolor,a.markerbgcolor,q.markerfillcolor),fillAlpha:c(a.markerfillalpha,q.markerfillalpha),fillAngle:c(a.markerfillangle,q.markerfillangle),fillRatio:c(a.markerfillratio,q.markerfillratio),fillPattern:c(a.markerfillpattern,q.markerbgpattern),hoverFillColor:a.markerfillhovercolor,hoverFillAlpha:a.markerfillhoveralpha,
hoverFillRatio:a.markerfillhoverratio,hoverFillAngle:a.markerfillhoverangle,borderThickness:c(a.markerborderthickness,1),borderColor:c(a.markerbordercolor,q.markerbordercolor),borderAlpha:g(a.markerborderalpha,q.markerborderalpha),hoverBorderThickness:a.markerborderhoverthickness,hoverBorderColor:a.markerborderhovercolor,hoverBorderAlpha:a.markerborderhoveralpha,radius:g(a.markerradius&&G.trimString(a.markerradius),7),shapeId:c(a.defaultmarkershape,"circle"),labelSepChar:c(a.labelsepchar,", "),tooltipSepChar:l.tooltipSepChar,
autoScale:g(a.autoscalemarkers,0),tooltext:c(f&&f.tooltext,a.markertooltext),dataEnabled:l.useValuesForMarkers,valueToRadius:g(a.markerradiusfromvalue,1),valueMarkerAlpha:c(a.valuemarkeralpha,"75"),hideNull:g(a.hidenullmarkers,0),nullRadius:g(a.nullmarkerradius,a.markerradius,7),adjustViewPort:g(a.adjustviewportformarkers,0),startAngle:g(a.markerstartangle,90),maxRadius:g(a.maxmarkerradius,0),minRadius:g(a.minmarkerradius,0),applyAll:g(a.applyallmarkers,0),shadow:g(a.showmarkershadow,a.showshadow,
0)},connectors:{showHoverEffect:g(a.showconnectorhovereffect,1),thickness:g(a.connectorthickness,a.markerconnthickness,"2"),color:c(a.connectorcolor,a.markerconncolor,q.markerbordercolor),alpha:c(a.connectoralpha,a.markerconnalpha,"100"),hoverthickness:g(a.connectorhoverthickness,a.connectorthickness,a.markerconnthickness,"2"),hovercolor:c(a.connectorhovercolor,a.connectorcolor,a.markerconncolor,q.markerbordercolor),hoveralpha:c(a.connectorhoveralpha,a.connectoralpha,a.markerconnalpha,"100"),dashed:g(a.connectordashed,
a.markerconndashed,0),dashLen:g(a.connectordashlen,a.markerconndashlen,3),dashGap:g(a.connectordashgap,a.markerconndashgap,2),font:c(a.connectorfont,a.markerconnfont,m),fontColor:c(a.connectorfontcolor,a.markerconnfontcolor,t),fontSize:g(a.connectorfontsize,a.markerconnfontsize,parseInt(u,10)),showLabels:g(a.showconnectorlabels,a.showmarkerlabels,a.showlabels,1),labelBgColor:c(a.connectorlabelbgcolor,a.markerconnlabelbgcolor,q.plotfillcolor),labelBorderColor:c(a.connectorlabelbordercolor,a.markerconnlabelbordercolor,
q.markerbordercolor),shadow:g(a.showconnectorshadow,a.showmarkershadow,a.showshadow,0),showTooltip:g(a.showconnectortooltip,a.showmarkertooltip,l.showTooltip),tooltext:c(f&&f.connectortooltext,a.connectortooltext),hideOpen:g(a.hideopenconnectors,1)},entities:{baseScaleFactor:this.baseScaleFactor,dataLabels:{style:{fontFamily:m,fontSize:u,lineHeight:B,color:h.plotOptions.series.dataLabels.color=t}},fillColor:L,fillAlpha:H,fillRatio:A,fillAngle:K,borderColor:C,borderAlpha:c(a.entityborderalpha,a.borderalpha,
this.borderAlpha,"100"),borderThickness:g(a.showentityborder,a.showborder,1)?g(a.entityborderthickness,a.borderthickness,1):0,scaleBorder:g(a.scaleentityborder,a.scaleborder,0),hoverFillColor:c(a.entityfillhovercolor,a.hoverfillcolor,a.hovercolor,q.plothoverfillcolor),hoverFillAlpha:c(a.entityfillhoveralpha,a.hoverfillalpha,a.hoveralpha,q.plothoverfillalpha),hoverFillRatio:c(a.entityfillhoverratio,a.hoverfillratio,a.hoverratio,q.plothoverfillratio),hoverFillAngle:c(a.entityfillhoverangle,a.hoverfillangle,
a.hoverangle,q.plothoverfillangle),hoverBorderThickness:c(a.entityborderhoverthickness,a.hoverborderthickness),hoverBorderColor:c(a.entityborderhovercolor,q.plotbordercolor),hoverBorderAlpha:c(a.entityborderhoveralpha,q.plotborderalpha),nullEntityColor:J,nullEntityAlpha:c(a.nullentityfillalpha,a.nullentityalpha,H),nullEntityRatio:c(a.nullentityfillratio,a.nullentityratio,A),nullEntityAngle:c(a.nullentityfillangle,a.nullentityangle,K),connectorColor:c(a.labelconnectorcolor,a.connectorcolor,t),connectorAlpha:c(a.labelconnectoralpha,
a.connectoralpha,"100"),connectorThickness:g(a.labelconnectorthickness,a.borderthickness,1),showHoverEffect:g(a.showentityhovereffect,a.usehovercolor,l.showHoverEffect),hoverOnNull:g(a.hoveronnull,a.entityhoveronnull,1),labelPadding:g(a.labelpadding,5),showLabels:g(a.showlabels,1),labelsOnTop:g(a.entitylabelsontop,1),includeNameInLabels:g(a.includenameinlabels,1),includeValueInLabels:g(a.includevalueinlabels,0),useSNameInTooltip:g(a.usesnameintooltip,0),useShortName:g(a.usesnameinlabels,1),labelSepChar:c(a.labelsepchar,
", "),showTooltip:g(a.showentitytooltip,l.showTooltip),tooltipSepChar:l.tooltipSepChar,tooltext:a.entitytooltext,hideNullEntities:g(a.hidenullentities,0),showHiddenEntityBorder:g(a.showhiddenentityborder,1),showNullEntityBorder:g(a.shownullentityborder,1),hiddenEntityColor:c(a.hiddenentitycolor,a.hiddenentityfillcolor,a.hiddenentityalpha||a.hiddenentityfillalpha?J:"ffffff"),hiddenEntityAlpha:c(a.hiddenentityalpha,a.hiddenentityfillalpha,.001),shadow:g(a.showshadow,this.defaultPlotShadow,q.shadow)},
entitydef:{useSNameAsId:g(a.usesnameasid,0)}});h.legend.title.style.lineHeight=fa(h.legend.title.style);h.legend.itemStyle.lineHeight=fa(h.legend.itemStyle);h.legend.itemHiddenStyle.lineHeight=fa(h.legend.itemHiddenStyle);f=Da(b,e,a.markermaxradius,a.markerminradius);h.markers.maxRadius=f.max;h.markers.minRadius=f.min;a.tooltipcolor&&(h.tooltip.style.color=ka(a.tooltipcolor));void 0!==c(a.clickurl)&&(k.link=a.clickurl,k.style.cursor="pointer",oa&&(k.style._cursor="hand"),h.plotOptions.series.point.events.click=
function(){k.events.click.call({link:a.clickurl})});f=k.bgImageDisplayMode;l=ua(a.bgimagevalign,"").toLowerCase();x=ua(a.bgimagehalign,"").toLowerCase();"tile"==f||"fill"==f||"fit"==f?("top"!=l&&"middle"!=l&&"bottom"!=l&&(l="middle"),"left"!=x&&"middle"!=x&&"right"!=x&&(x="middle")):("top"!=l&&"middle"!=l&&"bottom"!=l&&(l="top"),"left"!=x&&"middle"!=x&&"right"!=x&&(x="left"));k.bgImageVAlign=l;k.bgImageHAlign=x;this.parseStyles(h);fa(h.title.style);fa(h.subtitle.style);fa(h.tooltip.style);h.plotOptions.series.allowPointSelect=
!0;this.parseExportOptions(h);this.preSeriesAddition&&this.preSeriesAddition(h,d,b,e);this.series&&this.series(d,h,this.name,b,e);this.postSeriesAddition&&this.postSeriesAddition(h,d,b,e);this.spaceManager(h,d,b,e);W.console&&W.FC_DEV_ENVIRONMENT&&W.console.log(h);return h},series:function(b,e){function d(b){for(C=b&&b.length||0;C--;)w=b[C],r=w.value,w.cleanValue=a.getCleanValue(r),w.formattedValue=null!==w.cleanValue?a.dataLabels(r):void 0,w.origValue=r,null!==w.cleanValue&&(t=Q(w.cleanValue,t),
v=sa(w.cleanValue,v))}function h(a,b,d){for(C=a&&a.length||0;C--;){w=a[C];var f;a:{f=g(w.value);for(var h=void 0,k=void 0,h=void 0,m=E&&E.length||0;m--;)if(h=E[m],k=Number(h.maxvalue),h=g(h.minvalue,e.colorRange.scaleMin),f>=h&&f<=k){f=m;break a}f=null}F=f;null!==F&&(A="gradient"===u.type?e.colorRange.getColorObj(w.value).code:q&&q[F]&&c(q[F].color,q[F].code),y[F]||(y[F]=[]),A&&(w.color=w.color?w.color:A,b&&(w.alpha=w.alpha?w.alpha:b),d&&(p||w.fillhoveralpha||(w.fillhoveralpha=w.alpha),l||w.fillhovercolor||
(w.fillhovercolor=w.color)),y[F].push(w)))}}var a=this.numberFormatter,f=this.hcJSON.series,k=e.markers.valueMarkerAlpha,l=e.markers.hasHoverColor,p=e.markers.hasHoverAlpha,x=this.dataObj,m=e[ra],n=x.colorrange,q=n&&n.color,u=e.legend,y={},n={legendClick:function(){var a;if(a=this.chart)!this.legend&&(this.legend=this.plot.legend),a.legendClick(this,!this.visible)},getEventArgs:function(){var a;if(a=this.chart)return!this.legend&&(this.legend=this.plot.legend),a.getEventArgs(this)},setVisible:function(a){var b=
this.data,c=this.legendItem,e=this.visible;this.visible=a=void 0===a?!e:a;c&&u.colorizeItem&&u.colorizeItem(this,a);for(e=b&&b.length;e--;)(c=b[e].mapItem)&&(a?c.show&&c.show():c.hide&&c.hide())}},t=Infinity,v=-Infinity,w,A,D,E,r,F,B,C;d(x.data||[]);m.useValuesForMarkers&&d(x.markers&&x.markers.items||[]);m._doNotShowLegend=!0;u.type=x.colorrange&&"1"===x.colorrange.gradient?"gradient":"point";Infinity===t&&(t=void 0);-Infinity===v&&(v=void 0);m.dataMin=t;m.dataMax=v;e.colorRange=new G.colorRange({colorRange:x.colorrange,
dataMin:t,dataMax:v,defaultColor:u.minColor,numberFormatter:a});C=(E=e.colorRange.colorArr)&&E.length||0;if(0<C){for(;C--;)D=E[C],!m._doNotShowLegend||""===D.label&&void 0===D.label||(m._doNotShowLegend=!1),f.push(I({type:this.defaultSeriesType,showInLegend:!0,data:[],plot:{},name:D.label,color:D.code,rangeMin:D.minvalue,rangeMax:D.maxvalue,visible:!0},n));h(x.data||[]);m.useValuesForMarkers&&h(x.markers&&x.markers.items||[],k,!0);f=f.reverse();for(B in y)f[B]&&(f[B].data=y[B])}else f.push({type:this.defaultSeriesType,
data:[]});m._doNotShowLegend&&(this.hcJSON.legend.enabled=!1)},preliminaryScaling:function(b,c){for(var d=c.markers&&c.markers.items||[],h=d&&d.length||0,a=Infinity,f=Infinity,g=-Infinity,l=-Infinity,k,m;h--;)m=d[h],k=Number(m.x),m=Number(m.y),a=Q(a,k),f=Q(f,m),g=sa(g,k),l=sa(l,m);return{x:a,y:f,x1:g,y1:l}},getScalingParameters:function(b,c,d,h){var a=b/c,f=d/(b*this.baseScaleFactor),g=h/(c*this.baseScaleFactor),l=0,k=0;f>g?(f=g,l+=(d-h*a)/2,b=200/(c*f)):(k+=(h-d/a)/2,b=200/(b*f));return{scaleFactor:f,
strokeWidth:b,translateX:l,translateY:k}},calculateMarkerBounds:function(b,c,d,h,a){var f=b.markers,g=b[ra];b=g.dataMin;for(var g=g.dataMax,l=f.minRadius,k=f.maxRadius,m=f.hideNull,p=f.nullRadius,f=f.valueToRadius,n=(c=c.markers&&c.markers.items||[],c.length)||0,q=Infinity,u=Infinity,y=-Infinity,t=-Infinity,v,w,A;n--;)w=c[n],null!==w.cleanValue?(f&&void 0===w.radius&&(w.radius=l+(k-l)*(w.cleanValue-b)/(g-b)),A=Number(w.radius),v=(Number(w.x)+h)*d,w=(Number(w.y)+a)*d,q=Q(q,v-A),u=Q(u,w-A),y=sa(y,v+
A),t=sa(t,w+A)):m?w.__hideMarker=!0:void 0===w.radius&&(w.radius=p);return{x:q,y:u,x1:y,y1:t}},spaceManager:function(b,c,d,h){var a=b.chart,f=b[ra],g=a.spacingLeft,l=a.spacingTop,k=this.baseWidth,m=this.baseHeight;d-=a.spacingRight+g;a=h-(a.spacingBottom+l);h=f._captionBlock=this.manageTitleSpace(b,c,d,a);var p=f._legendBlock=this.placeLegendBlock(b,c,d,a-h.height,h.isBottom?h.height:0);d-=p.width;var a=a-h.height-p.height,n=p=0;f.useValuesForMarkers?(f.adjustViewPortForMarkers?(f=this.preliminaryScaling(b,
c),f.x1>k&&(k=f.x1),0>f.x&&(k+=-f.x,n=-f.x),f.y1>m&&(m=f.y1),0>f.y&&(m+=-f.y,p=-f.y),f=this.getScalingParameters(k,m,d,a),f=this.calculateMarkerBounds(b,c,f.scaleFactor*this.baseScaleFactor,n,p),b=a,c=d,0>f.x&&(g+=-f.x,d+=f.x),0>f.y&&(l+=-f.y,a+=f.y),f.x1>c&&(d-=f.x1-c),f.y1>b&&(a-=f.y1-b)):(f=this.getScalingParameters(k,m,d,a),this.calculateMarkerBounds(b,c,f.scaleFactor*this.baseScaleFactor,n,p)),f=this.getScalingParameters(k,m,d,a),g+=n*f.scaleFactor*this.baseScaleFactor,l+=p*f.scaleFactor*this.baseScaleFactor):
f=this.getScalingParameters(k,m,d,a);/bottom/i.test(h.position)||(l+=h.height);this.scaleFactor=f.scaleFactor;this.strokeWidth=f.strokeWidth;this.translateX=f.translateX+g;this.translateY=f.translateY+l},placeGLegendBlockRight:G.placeGLegendBlockRight,placeGLegendBlockBottom:G.placeGLegendBlockBottom,placeLegendBlock:function(b,c,d,h,a){var f=b.legend,g=b[ra],l=f.position.toLowerCase(),k={position:l};if("0"===c.chart.showlegend||g._doNotShowLegend)return k.height=0,k.width=0,k;"bottom"===l?(k.height=
"gradient"===f.type?this.placeGLegendBlockBottom(b,c,d,h):this.placeLegendBlockBottom(b,c,d,h),k.width=0,a&&(f.y=-a)):(d/=2,k.width="gradient"===f.type?this.placeGLegendBlockRight(b,c,d,h):this.placeLegendBlockRight(b,c,d,h),k.height=0);return k},manageTitleSpace:function(b,c,d,h){var a=this.hcJSON;b=a.title;c=a.chart;var a=a.subtitle,f=this.smartLabel,g=h/2,l=0,k=b.position.toLowerCase(),m=b.padding,p=!1,n=b.offsetX,q=b.offsetY,u=0,y={},t,v;if(""===b.text&&""===a.text)return{height:0,position:k};
isNaN(n)&&isNaN(q)||(p=!0,n=isNaN(n)?0:n,q=isNaN(q)?0:q);t=b.text;if(""!==t){f.setStyle(b.style);v=f.getOriSize(t);if(v.width>d||v.height>g)v=f.getSmartText(t,d,g),b.text=v.text,v.tooltext&&(b.originalText=v.tooltext);b.height=u=v.height;l+=u}g-=l;t=a.text;if(""!==t){f.setStyle(a.style);v=f.getOriSize(t);if(v.width>d||v.height>g)v=f.getSmartText(t,d,g),a.text=v.text,v.tooltext&&(a.originalText=v.tooltext);l+=a.height=v.height}l=l+m>g?g:l+m;k.match(/left/)?(a.align=b.align="start",a.x=b.x=c.marginLeft):
k.match(/right/)?(a.align=b.align="end",a.x=b.x=d):(a.align=b.align="middle",a.x=b.x=d/2);/bottom/.test(k)?(d=h-l+c.marginTop+m,b.y=d,a.y=d+u,p?(b.y+=q,a.y+=q,b.x+=n,a.x+=n):(c.marginBottom+=l,y.isBottom=!0)):p?(b.y+=q,a.y+=q,b.x+=n,a.x+=n):c.marginTop+=l;y.height=p?0:l;y.position=k;return y},getFirstId:function(){return this.firstEntity},getEntityPaths:function(b){var c={},d=this.entities,h;if(b){for(h in d)c[h]=d[h];return c}return d},redefineEntities:function(b,c){var d=this.entities,h={},a={},
f=0,g,l,k,m,n,p,q,u;for(q=b.length;q--;)if(g=b[q],l=g.internalid,n=g.newid?g.newid:l,k=g.sname,g=g.lname,m=d[l],l=G.trimString(l),n=G.trimString(n),m){h[n]=n={origId:l};a[l]=!0;for(p in m)n[p]=m[p];n.shortLabel=k?k:m.shortLabel;n.label=g?g:m.label}this.entities={};for(u in h)h[u].origId=u,this.entities[u.toLowerCase()]=h[u],f+=1;for(u in d)if(n=d[u],u=G.trimString(u),!a[u]){c.useSNameAsId?(this.entities[n.shortLabel.toLowerCase()]=m={},m.origId=n.shortLabel):(this.entities[u.toLowerCase()]=m={},m.origId=
u);for(p in n)m[p]=n[p];f+=1}this.entityCount=f},colorPaletteMap:{basefontcolor:"foregroundcolor",bordercolor:"foregrounddarkcolor",borderalpha:"foregrounddarkalpha",bgcolor:"backgroundlightcolor",bgalpha:"backgroundlightalpha",bgangle:"backgroundlightangle",bgratio:"backgroundlightratio",canvasbordercolor:"foregrounddarkcolor",canvasborderalpha:"foregrounddarkalpha",canvasbgcolor:"backgroundlightcolor",canvasbgalpha:"backgroundlightalpha",canvasbgangle:"backgroundlightangle",canvasbgratio:"backgroundlightratio",
tooltipbordercolor:"foregrounddarkcolor",tooltipborderalpha:"foregrounddarkalpha",tooltipbgcolor:"backgroundlightcolor",tooltipbgalpha:"backgroundlightalpha",tooltipfontcolor:"foregroundcolor",legendbordercolor:"foregrounddarkcolor",legendborderalpha:"foregrounddarkalpha",markerbordercolor:"foregroundlightcolor",markerborderalpha:"foregroundlightalpha",markerfillcolor:"backgrounddarkcolor",markerfillalpha:"backgrounddarkalpha",markerfillangle:"backgrounddarkangle",markerfillratio:"backgrounddarkratio",
plotfillcolor:"backgroundcolor",plotfillalpha:"backgroundalpha",plotfillangle:"backgroundangle",plotfillratio:"backgroundratio",plothoverfillcolor:"backgrounddarkcolor",plothoverfillalpha:"backgrounddarkalpha",plothoverfillangle:"backgrounddarkangle",plothoverfillratio:"backgrounddarkratio",plotbordercolor:"foregroundcolor",plotborderalpha:"foregroundalpha",shadow:"shadow"},eiMethods:{getMapName:function(){return this.jsVars.hcObj.logic.name},getEntityList:function(){var b=this.jsVars.hcObj,b=b.entities&&
b.entities.items,c,d=[],h,a;for(h in b)a=b[h],c=a.eJSON,d.push({id:a.id,originalId:a.originalId||a.id,label:c.label,shortlabel:c.shortLabel,value:a.value,formattedValue:a.formattedValue,toolText:a.toolText});return d},getDataAsCSV:function(){var b=this.jsVars,b=b.hcObj&&b.hcObj.entities&&b.hcObj.entities.items,c='"Id","Short Name","Long Name","Value","Formatted Value"',d,h,a,f;for(d in b)h=b[d],a=h.eJSON,f=h.value,c+='\r\n"'+h.id+'","'+a.shortLabel+'","'+a.label+'","'+(void 0===f?"":f)+'","'+h.formattedValue+
'"';return c},getMapAttribute:function(){var b=this.jsVars.fcObj;V.raiseWarning(this,"12061210581","run","JavaScriptRenderer~getMapAttribute()",'Use of deprecated "getMapAttribute()". Replace with "getChartAttribute()".');return b.getChartAttribute.apply(b,arguments)},exportMap:function(){var b=this.jsVars.fcObj;V.raiseWarning(this,"12061210581","run","JavaScriptRenderer~exportMap()",'Use of deprecated "exportMap()". Replace with "exportChart()".');return b.exportChart&&b.exportChart.apply(b,arguments)},
addMarker:function(b){this.jsVars.hcObj.markers.addMarkerItem(b)||V.raiseWarning(this,"1309264086","run","MapsRenderer~addMarker()","Failed to add marker. Check the options and try again.")},updateMarker:function(b,c){var d=this.jsVars.hcObj,h=d.markers,d=d.mapAnnotations,a;b&&(b=(b+"").toLowerCase(),h=h.items[b])&&(a=h.options,I(a,c),h=h.draw().markerShape,d.update(b,h))},removeMarker:function(b){var c=this.jsVars.hcObj.markers,d;b&&(b=(b+"").toLowerCase(),(d=c.items[b])&&d.destroy(),delete c.items[b])}}},
Z.linebase);Z("renderer.maps",{drawGraph:function(){var b=this,c=b.logic.chartInstance,d=b.paper,h=b.layers,a,f,g;b.options.nativeMessage||(h.dataset||(h.dataset=d.group("dataset").insertAfter(h.background),h.tracker=d.group("hot").insertAfter(h.dataset)),b.shadowLayer||(b.shadowLayer=h.shadow=d.group("shadow").insertBefore(h.dataset)),h.dataset&&h.dataset.hide(),h.shadow&&h.shadow.hide(),b.strokeWidth=b.logic.strokeWidth,a=b.logic.scaleFactor,b.translateX=f=b.logic.translateX,b.translateY=g=b.logic.translateY,
b.sFactor=a*b.logic.baseScaleFactor,b.transformStr=["t",f,",",g,"s",a,",",a,",0,0"].join(""),b.options.tooltip&&!1!==b.options.tooltip.enabled&&d.tooltip(b.options.tooltip.style,b.options.tooltip.shadow,b.options.tooltip.constrain),b.mapAnnotations=new G.Annotations,b.mapAnnotations.reset(null,{id:"geo",showbelow:0,autoscale:0,grpxshift:b.translateX?b.translateX:0,grpyshift:b.translateY?b.translateY:0,xscale:100*(b.sFactor?b.sFactor:1),yscale:100*(b.sFactor?b.sFactor:1),options:{useTracker:!0}}),
b.processEntityDefs(),b.drawEntities(),c.addEventListener("internal.mapdrawingcomplete",function(a){a.detachHandler();ya&&(h.dataset&&h.dataset.attr({transform:b.transformStr}),h.shadow&&h.shadow.attr({transform:b.transformStr}));h.dataset&&h.dataset.show();h.shadow&&h.shadow.show()}),b.drawMarkers())},setScaleRange:function(b,c){for(var d=this.options.series,g=d.length,a,f,k,l;g--;)if(k=d[g],f=(a=k.data)&&a.length)if(k.rangeMin>=b&&k.rangeMax<=c)k.setVisible(!0);else if(k.rangeMax<b||k.rangeMin>
c)k.setVisible(!1);else for(;f--;)k=(l=a[f].mapItem)&&l.value,isNaN(k)||""===k||(k>=b&&k<=c?l.show():l.hide())},processEntityDefs:function(){var b=this.logic,c=this.options.series,d=c&&c.length;for(b.redefineEntities(b.dataObj.entitydef||[],this.options.entitydef);d--;)c[d].chart=this},drawEntities:function(){this.entities=new m(this.logic&&this.logic.dataObj&&this.logic.dataObj.data,this,this.logic,this.layers.dataset)},drawMarkers:function(){var b=this.logic&&this.logic.dataObj&&this.logic.dataObj.markers||
null;b&&(this.markers=new y(b,this,this.group));this.options.entities.labelsOnTop||this.entities.drawLabels()},checkComplete:function(){var b=this.logic,c=b.chartInstance;this.entities&&this.entities.isReady()&&(this.mapAnnotations.draw(this),b.hasRendered=!0,V.raiseEvent("internal.mapdrawingcomplete",{renderer:this},c))}},Z["renderer.root"])},[3,2,0,"release"]]);
